import { type ChatSchema, generateRandomId } from './chat.atom';

export const FakeChatLogs: ChatSchema[] = [
  {
    id: generateRandomId(),
    userId: 'system', // System user for game logs
    message: 'Welcome to GawkGawk',
    isGameLog: true,
    role: 'viewer', // System messages can be viewer role for simplicity
  },
  {
    id: generateRandomId(),
    userId: 'user123',
    message: '0x1234 has joined the game',
    isGameLog: false,
    role: 'player',
  },
  {
    id: generateRandomId(),
    userId: 'coolcat',
    message: '0x1235 has joined the game',
    isGameLog: false,
    role: 'player',
  },
  {
    id: generateRandomId(),
    userId: 'system',
    message: '0x1236 has placed a bet',
    isGameLog: true,
    role: 'viewer',
  },
  {
    id: generateRandomId(),
    userId: 'luckyplayer',
    message: 'Welcome to GawkGawk',
    isGameLog: false,
    role: 'player',
  },
  {
    id: generateRandomId(),
    userId: 'user123',
    message: '0x1234 has joined the game',
    isGameLog: false,
    role: 'player',
  },
  {
    id: generateRandomId(),
    userId: 'coolcat',
    message: '0x1235 has joined the game',
    isGameLog: false,
    role: 'player',
  },
  {
    id: generateRandomId(),
    userId: 'system',
    message: 'Round started!',
    isGameLog: true,
    role: 'viewer',
  },
  {
    id: generateRandomId(),
    userId: 'gamerpro',
    message: 'glhf everyone!',
    isGameLog: false,
    role: 'player',
  },
  {
    id: generateRandomId(),
    userId: 'noobmaster69',
    message: 'Anyone know the rules?',
    isGameLog: false,
    role: 'viewer', // Let's make NoobMaster a viewer for fun
  },
  {
    id: generateRandomId(),
    userId: 'system',
    message: '0x1237 has placed a bet',
    isGameLog: true,
    role: 'viewer',
  },
  {
    id: generateRandomId(),
    userId: 'coolcat',
    message: 'Nice hand!',
    isGameLog: false,
    role: 'player',
  },
  {
    id: generateRandomId(),
    userId: 'luckyplayer',
    message: 'GG!',
    isGameLog: false,
    role: 'player',
  },
  {
    id: generateRandomId(),
    userId: 'user123',
    message: 'Revenge!',
    isGameLog: false,
    role: 'player',
  },
  {
    id: generateRandomId(),
    userId: 'system',
    message: 'Round ended. Payouts processing...',
    isGameLog: true,
    role: 'viewer',
  },
  {
    id: generateRandomId(),
    userId: 'gamerpro',
    message: 'Wow, almost had it!',
    isGameLog: false,
    role: 'player',
  },
  {
    id: generateRandomId(),
    userId: 'noobmaster69',
    message: 'Still confused lol',
    isGameLog: false,
    role: 'viewer',
  },
  {
    id: generateRandomId(),
    userId: 'system',
    message: '0x1238 has joined the game',
    isGameLog: true,
    role: 'viewer',
  },
  {
    id: generateRandomId(),
    userId: 'luckyplayer',
    message: 'Another round?',
    isGameLog: false,
    role: 'player',
  },
  {
    id: generateRandomId(),
    userId: 'system',
    message: 'New round starting in 5 seconds...',
    isGameLog: true,
    role: 'viewer',
  },
  {
    id: generateRandomId(),
    userId: 'coolcat',
    message: 'Lets go!',
    isGameLog: false,
    role: 'player',
  },
  {
    id: generateRandomId(),
    userId: 'user123',
    message: 'In again!',
    isGameLog: false,
    role: 'player',
  },
  {
    id: generateRandomId(),
    userId: 'system',
    message: 'Round started!',
    isGameLog: true,
    role: 'viewer',
  },
  {
    id: generateRandomId(),
    userId: 'gamerpro',
    message: 'Good luck everyone!',
    isGameLog: false,
    role: 'player',
  },
  {
    id: generateRandomId(),
    userId: 'luckyplayer',
    message: 'Lets win this time!',
    isGameLog: false,
    role: 'player',
  },
  {
    id: generateRandomId(),
    userId: 'system',
    message: '0x1239 has placed a bet',
    isGameLog: true,
    role: 'viewer',
  },
  {
    id: generateRandomId(),
    userId: 'noobmaster69',
    message: 'Okay, I think I get it now!',
    isGameLog: false,
    role: 'viewer',
  },
  {
    id: generateRandomId(),
    userId: 'coolcat',
    message: 'To the moon!',
    isGameLog: false,
    role: 'player',
  },
  {
    id: generateRandomId(),
    userId: 'user123',
    message: 'Lets get it!',
    isGameLog: false,
    role: 'player',
  },
  {
    id: generateRandomId(),
    userId: 'system',
    message: 'Round ended. Announcing winners...',
    isGameLog: true,
    role: 'viewer',
  },
];
